services:

  payment-gateway-e2e-tests:
    image: "payment-gateway-e2e-tests"
    build:
      context: .
      dockerfile: tests/PaymentGateway.EndToEnd.Tests/Dockerfile
    depends_on:
      - payment-gateway-api
      - wiremock
    environment:
        Services__Api__BaseUrl: http://payment-gateway-api:8081
    volumes:
      - ./docker/volumes/scripts:/app/scripts:ro
    command: >
      bash -c "scripts/wait-for-it.sh payment-gateway-api:8081 -t 30
      && scripts/wait-for-it.sh wiremock:8080 -t 30
      && dotnet test PaymentGateway.EndToEnd.Tests.dll"
